/// <reference path="../node_modules/@workadventure/iframe-api-typings/iframe_api.d.ts" />

WA.onInit().then(() => {
    WA.room.onEnterLayer("zone_random_portal").subscribe(() => {
        let random_number: number = Math.floor(Math.random() * all_exists.length);
        WA.nav.goToRoom("/@/rc3_21/" + all_exists[random_number] + "/main.json");
        // WA.nav.goToRoom(all_exists[random_number]);
    });
});


let all_exists: any = ["0x90", "1komona", "402", "Aaaaaaaaaaaa", "abchillgleis", "afoio", "afra", "akk", "ctbk", "hell", "anarchist-village", "artworld", "atka", "awareness", "backdoor", "bakery", "BalCCon", "bstly", "bc-WA", "cmsnord", "binhacken", "bitcoin", "bub", "bitwaescherei", "bogonauten", "Bordel", "burner-embassy-berlin", "bytespeicher", "bytewerk", "c3auti", "C3D2", "loc", "c3newsshow", "c3pb", "c3sign", "C3SRT", "C3WOC", "c-base", "ccc-basel", "cccch", "cccsbg", "cccwi", "cert", "c-hack", "chaosamsterdam", "c4", "CCCHH", "c3w", "c2is", "ChaosImLaborLuzern", "Chaosmentors", "c3e", "ChaosRiver", "csh", "chaostrawler", "CtAz", "chaostreffbern", "chch", "cccp", "chaoswelle", "cwtv", "chaoszone", "chaotisch_inkorrekt", "citylab", "CleanElectric", "club-haengemathe", "coffeenerds", "computertruhe", "computerwerk", "cogis", "c3s", "cyber4EDU", "cyberfirestation", "cyberyoga", "dachgeschoss", "darksystem", "daslabor", "deepcyber", "devbase", "devlol", "devtal", "dezentrale", "angelkitchen", "digitalcourage", "ebk", "glitzer", "esperanto", "e-waste", "fsim-ev", "fairydustforest", "fdroid", "fem", "fixme", "flipdot", "flying-objects", "airl", "fossag", "FOSSASIA", "frama", "franconian", "freeside", "fsfe", "ffc", "frubar", "fsfewomen", "fsrvi", "gaffa-overflow", "gelb", "GeraffelVillage", "hacc-muc", "h4-tw", "hacklabor", "hacknology", "hackthissite", "haecksen", "hsmr", "hoc", "heleum", "Helferlein", "himmel", "hs", "horny_jail", "hutzelbude", "icmp", "iconetfoundation", "intersect", "Irish", "it-syndikat", "kalkspace", "kinkygeeks", "klimbimwald", "KWAD", "labitat", "bib", "lebkuchis", "leinestelle511", "lobby", "lockpick", "lounge", "magnumchaos", "maglab", "mainframe", "Maked", "makerkids", "mch2022", "mv", "Mehlverkehr", "Metalab", "milliways", "MISChaufen", "mon2", "morgengrauen", "Multigeiger", "museum-of-status-codes", "museum-of-zzt", "nerdhof", "nerdraum", "neros-realm", "Moabit", "nixmuss", "nixos", "Nodeausgang", "nullaufeins", "nullmuseum", "numberwang", "okoyono", "openlabaux", "OpenScienceSCC", "osfw", "opensourcegardens", "osm", "ots", "PGspace", "phluse", "Pho", "photos", "poc", "portcarl", "PTL", "privacyweek", "r3s", "r4nd0m", "radiotipi", "RZL", "ravezeitarchiv", "infra", "reaktor23", "realtheorie", "realraum", "rlhx", "readventures", "RIOT-OS", "rcc", "rust", "samatrix", "schenklradio", "schokoladensouffle", "section77", "fha", "sendezentrum", "siliconforest", "silpion", "prost", "solicafe", "spacebi", "space-left", "spline", "sternenlabor", "stratum0", "swabian-embassy", "tabvillage", "telnet", "hack", "math", "moneybin", "TMS", "tomorrowland", "toplabberlin", "toppoint", "torservers-net", "tox", "unhb", "framasoft", "unterland", "vatican-embassy", "vbhf", "viout", "Turnhalle", "Vizak", "warpzone", "hswaw", "wtfeg", "WhistleblowVillage", "wikipaka", "xHain", "ztl", "z-labor", "V7", "muccc"];